# Generated by Django 3.0.8 on 2020-08-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
